name = "anime-cms"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "anime-cms"
database_id = "c7f361d4-3dfb-4dab-9262-6bbe8695f921"

# ADD THIS – KV binding for caching
[[kv_namespaces]]
binding = "KV"
id = "04422b70f04d48b2bb39dfcf9c3c0e99"